### ISSUE TITLE
 May I get the trained LoRA lib to reproduce the paper:Modular LLM?

### ISSUE THREAD

**Issue by Weifan1226** [microsoft/mttl#72] opened 2024-07-27 10:06 UTC
Hi Team！

I came across your excellent work on Modular LLM and would like to build upon it. Could you please provide the trained LoRA library used in your research to help me reproduce the results?

Thank you!

**Comment by Weifan1226** [comment] 2024-07-27 15:14
Hi Team,

Thank you so much for you help!
I truly appreciate your support!

Best regards,
Wei_fan

**Comment by sordonia** [comment] 2024-08-10 22:10
@shuishen112 thanks! closing the issue :)

**Closed by sordonia** 2024-08-10 22:10 UTC

**Comment by shuishen112** [comment] 2025-06-06 15:07
You can test this. zhan1993/mbc_library_phi2_icml

**Comment by kadarsh22** [comment] 2025-06-17 15:14
Thanks for providing the pretrained models to replicate the results. I tried replicating the results utilising the provided MBC library. However, the results obtained don't match those given in the paper. The results I obtained for MBC with uniform routing:

command : eval_library.py -k merge_or_route=uniform predict_batch_size=4 library_id=local:///mnt/fast/nobackup/scratch4weeks/ak03476/local_libraries/phi2/authors_mbc_10_experts device_map=cuda

where authors_mbc_10_experts is a clone of the hf://zhan1993/mbc_library_phi2_icml


+---------------+----------+----------+-------+-----------+-----------+-------+------------+-------+------------+-------+
| arc-challenge | arc-easy | bbh-fast | boolq | hellaswag | humaneval |  mbpp | openbookqa |  piqa | winogrande |  mean |
+---------------+----------+----------+-------+-----------+-----------+-------+------------+-------+------------+-------+
|     0.521     |  0.761   |  0.480   | 0.832 |   0.733   |   0.451   | 0.599 |   0.492    | 0.791 |   0.755    | 0.641 |
+---------------+----------+----------+-------+-----------+-----------+-------+------------+-------+------------+-------+

And with arrow routing :

eval_library.py -k merge_or_route=arrow predict_batch_size=4 library_id=local:///mnt/fast/nobackup/scratch4weeks/ak03476/local_libraries/phi2/authors_mbc_10_experts device_map=cuda

+---------------+----------+----------+-------+-----------+-----------+-------+------------+-------+------------+-------+
| arc-challenge | arc-easy | bbh-fast | boolq | hellaswag | humaneval |  mbpp | openbookqa |  piqa | winogrande |  mean |
+---------------+----------+----------+-------+-----------+-----------+-------+------------+-------+------------+-------+
|     0.538     |  0.775   |  0.461   | 0.830 |   0.731   |   0.500   | 0.619 |   0.526    | 0.798 |   0.759    | 0.654 |
+---------------+----------+----------+-------+-----------+-----------+-------+------------+-------+------------+-------+

Do you have any suggestions on what could be causing this difference in results? Also, attaching the obtained logs for your reference

[authors_mbc_arrow.log](https://github.com/user-attachments/files/20778248/authors_mbc_arrow.log)

**Comment by shuishen112** [comment] 2025-06-17 15:30
sry, the main branch updated. You need to add a space because it is included in the pretraining of this library. 

https://github.com/microsoft/mttl/commit/380b27baa11a67f849098f4db78a0cb7c63cd45f

please add the space in your current code.

**Comment by kadarsh22** [comment] 2025-06-17 18:42
Thanks @shuishen112 for the quick response, I tried adding the space, which increased the performance of MBC with arrow routing to 66.57%, and on adding the parameter 'add_special_tokens=False', the result further improved to 66.7%, which still falls short of 67.4%.  It would be great if you could recollect any other changes that is required for reproducing the same results.

Arrow Routing MBC with (" " + self.tokenizer.eos_token) only

+---------------+----------+----------+-------+-----------+-----------+-------+------------+-------+------------+-------+
| arc-challenge | arc-easy | bbh-fast | boolq | hellaswag | humaneval |  mbpp | openbookqa |  piqa | winogrande |  mean |
+---------------+----------+----------+-------+-----------+-----------+-------+------------+-------+------------+-------+
|     0.573     |  0.844   |  0.465   | 0.836 |   0.734   |   0.500   | 0.607 |   0.526    | 0.801 |   0.771    | 0.666 |
+---------------+----------+----------+-------+-----------+-----------+-------+------------+-------+------------+-------+

Arrow Routing MBC with  'add_special_tokens=False and (" " + self.tokenizer.eos_token)
+---------------+----------+----------+-------+-----------+-----------+-------+------------+-------+------------+-------+
| arc-challenge | arc-easy | bbh-fast | boolq | hellaswag | humaneval |  mbpp | openbookqa |  piqa | winogrande |  mean |
+---------------+----------+----------+-------+-----------+-----------+-------+------------+-------+------------+-------+
|     0.573     |  0.845   |  0.463   | 0.837 |   0.734   |   0.500   | 0.615 |   0.530    | 0.803 |   0.773    | 0.667 |
+---------------+----------+----------+-------+-----------+-----------+-------+------------+-------+------------+-------+

[authors_after_code_update.log](https://github.com/user-attachments/files/20781972/authors_after_code_update.log)
