### ISSUE TITLE
On the details of Arrow Routing

### ISSUE THREAD

**Issue by Weifan1226** [microsoft/mttl#107] opened 2024-09-01 15:46 UTC
Hi Team! 

I have recently been working on implementing the Arrow Routing algorithm in my project. However, I'm facing a challenge due to my limited expertise, particularly in understanding the concept of "token in layer l" within the algorithm. My current understanding is that the hidden state post the attention layer serves as h_l. However, the output of a transformer layer is typically structured as [batch_size, tokens, hidden_size]. I am uncertain about how to proceed from this point.

Additionally, I am seeking clarity on the phrase "it routes differently in every layer and token, increasing the overall model expressivity." Does this imply a "per token" routing mechanism? My interpretation is that the output of each transformer layer determines the subsequent LoRA adjustments to be made to the transformer layer.

![截屏2024-09-01 23 25 38](https://github.com/user-attachments/assets/5094d948-9f37-4fce-bc19-9fce7dfe5b2c)

I would appreciate any guidance or insights you could provide to help me better understand these aspects of the Arrow Routing algorithm.

Thank you!

Best regards,
Fanjunduo Wei

**Comment by Weifan1226** [comment] 2024-09-02 05:38
I seem to understand the concept of "per token", just like MoE router. But my new question is: if Arrow Router selects LoRA A based on token a and LoRA B based on token b, then after processing token a in base model+A, do I need to eliminate the weight of LoRA A, reload LoRA B into the base model and then process token b?

**Comment by pclucas14** [comment] 2024-09-04 02:11
Hi!

Thanks for your interest in our work. Let me try and clarify Arrow routing. 
Just like an MoE router, each token at each layer is routed individually. One difference however is that in your typical MoE, tokens are routed to MLP / FFN experts, whereas our experts are simple linear layers. 

For example, on the [Mistral model](https://github.com/huggingface/transformers/blob/main/src/transformers/models/mistral/modeling_mistral.py#L146), say that we train LoRAs on the `gate_proj`, `up_proj` and `down_proj` of the MLP layer. Then, for each of `gate_proj`, `up_proj` and `down_proj` we have a LoRA adapter,  meaning that for a given MLP block each token will get routed 3 times, once for each linear layer. In a standard MoE, each token would get routed once per MLP expert. 

I am not sure I fully understood the last point regarding LoRA As and Bs. Whenever a token is routed to a given LoRA expert, that token will be processed by both the `A` and `B` projections of the LoRA adapter. 

Hopefully that clarifies a few things!
Lucas

**Comment by herkerser** [comment] 2024-09-13 03:09
Hi Team!

I have recently been working on implementing the Arrow Routing algorithm in my project. However,  I'm facing a challenge due to my limited expertise, particularly in understanding the concept of the "first right singular vector" within the algorithm. In the algorithm, the V matrix is utilized. Then, I roughly went through the code and found that matrix U is used to calculate the top vector. Why is that?
![image](https://github.com/user-attachments/assets/ab3462ad-bfc5-41c3-b2ad-26baab9581ee)

**Comment by pclucas14** [comment] 2024-09-16 13:16
Hi, 

Thanks for reaching out. This is because our notation in the paper does not quite match our implementation. In the code we use `output = (W + BA)x`, while in the paper we use `output = (W + AB)x`. So if you transpose the matrix the Us become the  Vs and vice versa

**Comment by pclucas14** [comment] 2024-09-24 23:54
Hi @herkerser, did you end up solving your issue ?

**Comment by herkerser** [comment] 2024-09-27 06:08
yes, thank you! 

> Hi @herkerser, did you end up solving your issue ?

**Comment by herkerser** [comment] 2024-09-27 06:25
However, I do have another problem understanding, if the rank is 32, the original layer is a linear layer which is sized 4096*11008, Then how can we utilize the arrow routing? (Since the dimension of input token is 4096 while that of V matrix is 11008)

**Comment by pclucas14** [comment] 2024-09-27 18:57
For any base layer `d_in x d_out`, Arrow first does a SVD decomposition into three matrices of shape `d_in x d_in`, `d_in x d_out`, `d_out x d_out`. Arrow then takes the first entry in the `d_in x d_in` matrix as prototype. 

Arrow routing will work regardless of the rank. No matter what your rank is, `lora_a x lora_b` which is `d_in x r` x `r x d_out` will give you a matrix of the same size as the base layer you are "patching" with a LoRA

**Comment by saksham20aggarwal** [comment] 2024-10-04 23:06
Hi @pclucas14 ! I was trying to reproduce the Arrow results. I noticed that default top_k for arrow routing is kept as -1 which means it wont do top_k at all whereas in the paper top_k=4. Can you clarify what exactly do you keep top_k as?

**Comment by pclucas14** [comment] 2024-10-08 14:57
HI @saksham20aggarwal, you are right! it should be set to `4`. I will submit a PR to change the default value.

**Comment by sordonia** [comment] 2024-10-18 13:50
@pclucas14  can i close this ?

**Closed** 2024-10-22 20:19 UTC
